version: '3'
services:
    redis:
      image: redis:alpine
      ports:
        - 6379:6379
      container_name: redis
      volumes:
      - redis-data:/data
    redis-cli:
      image: redis:alpine
      volumes:
        - scripts:scripts
      entrypoint: sh -c scripts/redis-init.sh

    mysql-db:
      image: mysql:latest
      container_name: mysql-db
      ports:
        - 3306:3306
      environment:
        MYSQL_ROOT_PASSWORD: test
        MYSQL_DATABASE: maclaren
      volumes:
        - mysql-data:/var/lib/mysql
    order:
      build: 
        context: .
        args: 
          PROJECT_NAME: "order"
      env_file:
          - order/.env
      ports:
        - 8080:8080
      depends_on:
        - redis
    order_processor:
      build: 
        context: .
        args: 
          PROJECT_NAME: "order_processor"
      command: cat order_processor/order_processor.lua | redis-cli -x FUNCTION LOAD REPLACE
      env_file:
          - order_processor/.env
      depends_on:
        - redis
        - mysql-db
      links:
        - mysql-db
 
volumes:
  mysql-data:
  redis-data:
  scripts:

    
    
    
    